import type { MemoryRecord, MemoryType } from '@/types/governed';
import { loadRegistry } from './registry';
import { evaluatePolicy, defaultScope, POLICY_FILTERS, type ScopeRequest } from './scope';
import { buildIndex } from './index-tree';
import { DEFAULT_FLOOR } from './evidence';

/**
 * `memrails.md` projection — contract v0.1 §7.
 *
 * Projects the governed store into a single derived markdown file: structure
 * from the MemoryIndex tree, content from a governed scoped read (the same
 * policy gates as retrieval — scope, status, sensitivity, expiry — plus the
 * §5.5 evidence floor). The output is a DERIVED ARTIFACT: regenerable at any
 * time, never a write surface, and it ends with a trace footer explaining
 * exactly what was included and what was withheld.
 */

export type ProjectMdOptions = {
  owner_id?: string;
  project_id?: string;
  agent_id?: string | null;
  /** `sensitive` records are excluded unless explicitly requested (§7). */
  include_sensitive?: boolean;
  /** Evidence floor; records below it do not project (§5.5, default 0.75). */
  floor?: number;
  /** Injected clock for deterministic output in tests. */
  now?: () => string;
};

export type ProjectMdStats = {
  scope: { owner_id: string; project_id: string; agent_id?: string | null };
  included: number;
  omitted: Record<string, number>;
  branches: string[];
  floor: number;
  generated_at: string;
};

export type ProjectMdResult = {
  markdown: string;
  stats: ProjectMdStats;
};

/** Section order mirrors how much a fresh agent should trust each type. */
const SECTION_ORDER: Array<{ type: MemoryType; title: string }> = [
  { type: 'decision', title: 'Decisions' },
  { type: 'constraint', title: 'Constraints' },
  { type: 'preference', title: 'Preferences' },
  { type: 'correction', title: 'Corrections' },
  { type: 'claim', title: 'Claims' },
  { type: 'note', title: 'Notes' },
  { type: 'summary', title: 'Summaries' },
  { type: 'extraction', title: 'Extractions' },
];

function renderRecord(record: MemoryRecord): string {
  const conf = record.confidence.toFixed(2);
  const lines = [`- ${record.summary} (confidence ${conf} · \`${record.memory_id}\` · ${record.source_file})`];
  if (record.content !== record.summary && record.content.length <= 400) {
    lines.push(`  > ${record.content.replace(/\n+/g, ' ')}`);
  }
  if (record.contradictions.length > 0) {
    lines.push(`  > ⚠ contradicts: ${record.contradictions.map((c) => `\`${c}\``).join(', ')}`);
  }
  return lines.join('\n');
}

export function projectMarkdown(opts: ProjectMdOptions = {}): ProjectMdResult {
  const scope: ScopeRequest = defaultScope({
    owner_id: opts.owner_id,
    project_id: opts.project_id,
    agent_id: opts.agent_id ?? null,
  });
  const floor = opts.floor ?? DEFAULT_FLOOR;
  const generated_at = (opts.now ?? (() => new Date().toISOString()))();

  const omitted: Record<string, number> = {};
  const bump = (reason: string) => {
    omitted[reason] = (omitted[reason] ?? 0) + 1;
  };

  // Governed read: the exact policy gates retrieval applies, then the
  // projection-specific gates (sensitive opt-in, evidence floor).
  const projected: MemoryRecord[] = [];
  for (const record of loadRegistry()) {
    const decision = evaluatePolicy(record, scope);
    if (!decision.allowed) {
      // Tenancy rejections aren't interesting in the footer; governance ones are.
      if (record.scope.owner_id === scope.owner_id && record.scope.project_id === scope.project_id) {
        bump(decision.reason);
      }
      continue;
    }
    if (record.status !== 'active') {
      bump(record.status);
      continue;
    }
    if (record.sensitivity === 'sensitive' && !opts.include_sensitive) {
      bump('sensitive_excluded');
      continue;
    }
    if (record.confidence < floor) {
      bump('below_floor');
      continue;
    }
    projected.push(record);
  }

  const index = buildIndex(projected);
  const branches = index.nodes
    .filter((n) => n.member_ids.length > 0)
    .map((n) => n.path)
    .sort();

  const out: string[] = [];
  out.push('<!-- DERIVED ARTIFACT — generated by `memrails project-md` (contract v0.1 §7).');
  out.push('     Do not edit: changes here are lost on the next projection. Write through');
  out.push('     memory.write() / the governed store and regenerate. -->');
  out.push('');
  out.push(`# memrails.md — ${scope.project_id}`);
  out.push('');
  out.push(
    `> Governed projection of ${projected.length} active memories (floor ${floor}, ` +
      `restricted excluded${opts.include_sensitive ? ', sensitive included' : ''}). ` +
      `Generated ${generated_at}.`,
  );

  for (const section of SECTION_ORDER) {
    const records = projected
      .filter((r) => r.memory_type === section.type)
      .sort((a, b) => b.confidence - a.confidence || a.memory_id.localeCompare(b.memory_id));
    if (records.length === 0) continue;
    out.push('');
    out.push(`## ${section.title}`);
    out.push('');
    for (const record of records) out.push(renderRecord(record));
  }

  out.push('');
  out.push('## Memory map');
  out.push('');
  for (const path of branches) {
    const node = index.nodes.find((n) => n.path === path)!;
    out.push(`- \`${path}\` — ${node.member_ids.length} memories`);
  }

  // Trace footer (§7): the projection explains itself like a bundle does.
  out.push('');
  out.push('---');
  out.push('');
  out.push('```yaml');
  out.push('# retrieval trace — memrails.md projection');
  out.push(`scope: { owner: ${scope.owner_id}, project: ${scope.project_id}, agent: ${scope.agent_id ?? 'null'} }`);
  out.push(`policy_filters_applied: [${POLICY_FILTERS.join(', ')}]`);
  out.push(`evidence_floor: ${floor}`);
  out.push(`branches: ${branches.length}`);
  out.push(`memories_included: ${projected.length}`);
  const omittedPairs = Object.entries(omitted).sort(([a], [b]) => a.localeCompare(b));
  out.push(
    omittedPairs.length > 0
      ? `memories_omitted: { ${omittedPairs.map(([k, v]) => `${k}: ${v}`).join(', ')} }`
      : 'memories_omitted: {}',
  );
  out.push(`generated_at: ${generated_at}`);
  out.push('```');
  out.push('');

  return {
    markdown: out.join('\n'),
    stats: {
      scope: { owner_id: scope.owner_id, project_id: scope.project_id, agent_id: scope.agent_id },
      included: projected.length,
      omitted,
      branches,
      floor,
      generated_at,
    },
  };
}
